#!/bin/bash
# if there are no cli arguments:
date
#dataFolder="scopeTest"
if [ $# -eq 0 ]; then
	# use defaults
	echo -e "[ dataWrangler ] No arguments, using defaults."
	dataFolder="../../DataSets/ml-20m/"
else
	echo -e "[ dataWrangler ] Arguments provided, setting."
	dataFolder=$1
fi

# debug
python ./Misc/debug.py
# data preperation
python ./Misc/movieLenseWrangler.py $dataFolder
python ./Misc/movieLenseDataCombiner.py $dataFolder
python ./Misc/monteCarlo.py $dataFolder "pML.csv"
# learning algorithms
python ./Misc/knn.py $dataFolder "test.csv" "train.csv" &
mlpack_knn --reference_file=${dataFolder}train.csv --output_model_file=${dataFolder}mlpack_model_knn_out.txt
#wait
