# @Author: archer
# @Date:   2019-09-13T12:52:06+01:00
# @Last modified by:   archer
# @Last modified time: 2020-02-28T14:34:24+00:00



# set environment variables using .env file located in this same directory
version: "3.7"

services:

  # by default uses local files and copies them into docker
  # if you prefer a more sable version swap the commented context call
  # with the uncommented one.
  nemesyst:
    build:
      # this is the stable/ longer term (ubuntu) version:
      # context: ./examples/containers/nemesyst_ubuntu
      # this is the archlinux on the edge version, it is very big (+10G):
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb_server
    # this is the official image name to use so we dont have to create one
    image: "mongo"
    ports:
      # this maps one of our local ports to one of the containers ones
      # "local-port:container-port"
      - "65530:27017"
    command:
      - "--config"
      - "/etc/mongodb.conf" # this is the in container path
      # be warned our config file uses additional options like directoryPerDB
      # which may make it not work with existing databases, if in doubt just
      # use your own config file and change the volume path below
    volumes:
      # this is the location to mount in container and storage for db
      # "volume-name:in-container mount point (not local system):"
      # or /local/location:/docker/location
      # - "mongodb-volume:/data/db"
      - /data/db:/data/db
      # local file:docker vm location # this copies over the config file
      # This will copy local config file to docker container
      # - /etc/mongodb.conf:/etc/mongodb.conf
      - ./examples/configs/mongo/mongo_docker.yaml:/etc/mongodb.conf
